name: messenger
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ionicons: ^0.1.2

  cupertino_icons: ^1.0.2
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/face.png
    - images/mess.png
    - images/user1.jpg
    - images/user2.jpg
    - images/user3.jpg
    - images/user4.jpg
    - images/user5.jpg
    - images/user6.jpg
    - images/user7.jpg
    - images/user8.jpg
    - images/user9.jpg
    - images/user10.jpg
    - images/user11.jpg
    - images/user12.jpg
    - images/user13.jpg
    - images/avt.jpg
    - images/gmail1.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

